### ISSUE TITLE
Dead links in cadastrapp

### ISSUE THREAD

**Issue by severo** [georchestra/datadir#123]
See:

https://github.com/georchestra/datadir/blob/d1721391786989c3e6065180c62c653ba68f3a67/cadastrapp/cadastrapp.properties#L46

https://github.com/georchestra/datadir/blob/d1721391786989c3e6065180c62c653ba68f3a67/cadastrapp/cadastrapp.properties#L53

**Comment by fvanderbiest** [comment]
Maybe we should replace them with georchestra.mydomain.org because they're meant to be replaced by local FQDN.

**Comment by fvanderbiest** [comment]
linked with https://github.com/georchestra/georchestra/issues/2303

**Comment by fvanderbiest** [comment]
removed references to cadastrapp
