### ISSUE TITLE
cas urls in security-proxy.properties should use publicUrl

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#126]
there are still https://georchestra.mydomain.org occurences in https://github.com/georchestra/datadir/blob/master/security-proxy/security-proxy.properties#L9 - with all the work that's been done to sanitize properties & use values from `defaults.properties`, can those entries use `publicUrl` from the defaults ?

**Comment by severo** [comment]
There are occurrences in almost all the modules:

```
README.md:Before using this datadir, you should at least change the default FQDN (`georchestra.mydomain.org`) for yours.
README.md:find ./ -type f -exec sed -i 's/georchestra.mydomain.org/my.fqdn/' {} \;
atlas/atlas.properties:atlas.baseUrl=https://georchestra.mydomain.org/atlas
cas/cas.properties:server.name=https://georchestra.mydomain.org
cas/cas.properties:server.prefix=https://georchestra.mydomain.org/cas
cas/cas.properties:host.name=georchestra.mydomain.org
console/console.properties:replyTo=georchestra+testadmin@georchestra.mydomain.org
console/console.properties:from=georchestra+testadmin@georchestra.mydomain.org
default.properties:publicUrl=https://georchestra.mydomain.org
extractorapp/extractorapp.properties:# publicUrl=https://georchestra.mydomain.org
mapfishapp/credentials.properties:georchestra.mydomain.org=geoserver_privileged_user:gerlsSnFd6SmM
mapfishapp/js/GEOR_custom.js:    EDITABLE_LAYERS: /.*georchestra.mydomain.org.*/i,
mapfishapp/print/config.yaml:      host: georchestra.mydomain.org
mapfishapp/wfs.servers.json:            "url": "https://georchestra.mydomain.org/geoserver/wfs"
mapfishapp/wms.servers.json:            "url": "https://georchestra.mydomain.org/geoserver/wms"
mapfishapp/wmts.servers.json:            "url": "https://georchestra.mydomain.org/geoserver/gwc/service/wmts"
security-proxy/security-proxy.properties:logout-success-url=https://georchestra.mydomain.org/cas/logout?fromgeorchestra
security-proxy/security-proxy.properties:casLoginUrl=https://georchestra.mydomain.org/cas/login
security-proxy/security-proxy.properties:casTicketValidation=https://georchestra.mydomain.org/cas
security-proxy/security-proxy.properties:proxyCallback=https://georchestra.mydomain.org/login/cas
```

as a result of not filtering the properties files anymore (before, the `${publicUrl}` instances inside properties files were replaced by the corresponding value from default.properties)

**Comment by severo** [comment]
Three options:

1. let it as is, and the administrator will have to change all the occurrences
2. change the meaning of these properties, for example: instead of `atlas.baseUrl=https://georchestra.mydomain.org/atlas`, set `atlas.baseUrl=/atlas` and prefix with `https://georchestra.mydomain.org` (or more exactly the content of `publicUrl`) in the code, where the property is loaded.
3. Add the possibility to filter the properties inside the [GeorchestraConfiguration](https://github.com/georchestra/georchestra/blob/18.12/commons/src/main/java/org/georchestra/commons/configuration/GeorchestraConfiguration.java) class to reproduce the previous behavior (replace placeholders in properties files with properties values from [default.properties](https://github.com/georchestra/datadir/blob/18.12/default.properties).

**Comment by fvanderbiest** [comment]
I think Landry is mostly interested in `security-proxy/security-proxy.properties` and `cas/cas.properties` (maybe also `atlas/atlas.properties`).

Option 3 looks good to me. 

@pmauduit what's your opinion ?

**Comment by landryb** [comment]
Yes, it feels wrong to have to set the url in so many places (which is explained in https://github.com/georchestra/datadir/#3-steps-editing and feels awkward, one should just have to set `publicUrl` in `default.properties`), especially now that we have a default

**Comment by severo** [comment]
OK. I will work on this. This implies removing all the spring placeholders, and only use the GeorchestraConfiguration class/bean to access the properties. I will create issues based on that.

**Comment by pmauduit** [comment]
About the grep from the comment https://github.com/georchestra/datadir/issues/126#issuecomment-462316348, the remaining .properties files in the georchestra codebase are just meant to provide default values, they are anyway overriden by the georchestra.datadir Java system properties. I'd prefer to leave them as it is (or else, we can remove the properties file, but I suspect it will break some setups - e.g. mvn jetty:run).

I'm also ok with the option 3. but sometimes it should not be necessary, depending on how the variables are resolved (if it is via the spring xml configuration, there is probably nothing to do, the variables will be resolved).

> OK. I will work on this. This implies removing all the spring placeholders, and only use the GeorchestraConfiguration class/bean to access the properties. I will create issues based on that.

I'd try to rely on the spring placeholders, which sounds more reliable than the geOrchestra configuration. there should be less places where the variables are resolved via the GeorchestraConfiguration bean, than via the placeholders.

**Comment by severo** [comment]
I don't understand how to do... If we allow to use variables like `publicUrl` in datadir properties, we need a mechanism to replace them with the corresponding value. With spring placeholders, there is no way of doing this (there was, but we remove it)

**Comment by pmauduit** [comment]
> I don't understand how to do... If we allow to use variables like `publicUrl` in datadir properties, we need a mechanism to replace them with the corresponding value. With spring placeholders, there is no way of doing this (it was possible with the config module, but we removed it)

I thought that spring could resolve the variables from one properties file on another, e.g. if I have a `publicUrl` defined in the `default.properties`, then loading a `cas.properties` containing for example a `baseUrl=${publicUrl}/cas`, it would be resolved as expected.

**Comment by severo** [comment]
No, it cannot.

**Comment by fvanderbiest** [comment]
> I thought that spring could resolve the variables from one properties file on another

If that's not possible, what about having an environment variable for `baseURL` ?

**Comment by severo** [comment]
Even if it comes from an environment variable, we need a mechanism to replace the placeholders, it would n't be automatic.

**Comment by severo** [comment]
Linked to https://github.com/georchestra/georchestra/issues/2379

**Comment by severo** [comment]
For 3, we could use https://github.com/georchestra/georchestra/issues/2379#issuecomment-457852572 to replace all the occurrences of placeholders

**Comment by fvanderbiest** [comment]
See also https://github.com/georchestra/georchestra/issues/2496

**Comment by severo** [comment]
See #137.
