### ISSUE TITLE
Comment all the properties in datadir (and harmonize the format of properties files)

### ISSUE THREAD

**Issue by severo** [georchestra/datadir#129]
All the properties are (should be) loaded with Spring placeholders in the applications, with a default value in case the property does not exist.

In order to facilitate the tasks of the administrator, we could use that following pattern in the properties file (it's the common way of doing in .conf files in /etc/ in GNU/Linux distributions):

```
# The maximum in memory size allowed
# Default is 10240
# See also: see https://docs.spring.io/autorepo/docs/spring-framework/3.1.0.RELEASE/javadoc-api/org/springframework/web/multipart/commons/CommonsFileUploadSupport.html#setMaxInMemorySize(int)
#maxInMemorySize=10240
```

- the property is commented (the administrator will uncomment if they want to change the value)
- it's preceded by a comment on what the property is, and on its default value, that must be equal to the value in the commented line

And obviously, this value should also correspond to the default value in the code when it's accessed via a placeholder, eg:

```
    <property name="maxInMemorySize" value="${maxInMemorySize:10240}"/>
```

**Comment by fvanderbiest** [comment]
Well, this makes sense, even it feels weird to have nearly all values commented in a blank datadir !

**Comment by severo** [comment]
From my point of view:

- it's way easier for the administrator to configure these files: with a correctly configured editor, you directly see which properties are different from the default value (uncommented, generally displayed in white on black), and which properties will use the default value (commented, generally displayed in grey on black). The contrast helps a lot to navigate in these files.
- it also gives confidence to the administrator for its first steps: they only let the files untouched, or modify one or two parameters, and all should work as expected. And when they are a bit more experienced with geOrchestra, they will touch other parameters.
- currently, the administrator feels like they have to understand what every parameter does before trying geOrchestra, and it's uncomfortable (well, it was my feeling when I first approached geOrchestra, even if the configuration management was a bit different).

**Comment by severo** [comment]
> in a blank datadir

Well, the datadir contains a lot more than properties files (maybe it's another issue, by the way)

**Comment by severo** [comment]
TODO: for each property in an application properties file (and also for default.properties):

- verify that 1. a default value is set in every placeholder that calls it in geOrchestra code, 2. this default value is the same, if it's called in different places
- comment the value, and add a description + the default value on the previous line, as for example:

```
# Max time unused connections are kept idle in the pool. Unit is seconds for c3p0.
# default: 60
#dataSource.maxIdleTime=60
```

- test that no regression has been introduced.

**Comment by severo** [comment]
See #138
