### ISSUE TITLE
Cannot create account or modify password

### ISSUE THREAD

**Issue by chester59240** [georchestra/datadir#190]
Hello,

I'm having troubles while configuring Georchestra! I cannot create account.
When I try to generate a password for one user by sending email =>{"success":false,"error":"com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.1 Authentication required\n"}

I correctly configured my SMTP parameters, I can receive test message.
According to the "Authentification required" message, I would say that my configuration in administration parameter isn't used.
So I tried to force them in default.properties and console.properties but there is nothing about a password I should specify...

Like an authentification e-mail and password on the SMTP server...

Is there something I am missing?

Thanks for help!

**Comment by fvanderbiest** [comment]
Yes, It's a long standing issue, see https://github.com/georchestra/georchestra/issues/998
In the mean time you can use a smtp proxy which will add the auth parameters

**Comment by chester59240** [comment]
As suggested, I used proxy. 
I tried Exim4 but I couldn't make it work...  Postfix is OK! :)
