### ISSUE TITLE
mapstore/localConfig.json is outdated

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#213]
this had to happen ofc :)

should be kept in sync with https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json ...

**Comment by landryb** [comment]
fixed by #214 ?

**Comment by fvanderbiest** [comment]
I don't know.
More generally, this raises the question of maintaining things for someone else's sake. It's ... difficult.
Who's responsible for MapStore ? If the mapstore datadir does not get maintained, we'll have no option but to remove the mapstore folder from the datadir.

**Comment by fvanderbiest** [comment]
See also #218

**Comment by landryb** [comment]
#224 & #229 also updated it, and let's say i'm taking responsability for syncing those damn config files, someone has to do it at some point ;)
