### ISSUE TITLE
mapstore2 extensions folder and file

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/datadir#227]
The `mapstore/README.md` contains a extensions.json detail  :

> extensions.json: dynamic registry of currently installed extensions, in JSON format

But we have nothing about that when we clone the datadir.
From last release, we have a new folder `extensions` to contains `extensions.json` file.

Btw, I think that we could provide this folder and a ready `extensions.json` file to avoid default install error.

I will create a PR next.

**Comment by landryb** [comment]
makes sense, thanks !
