### ISSUE TITLE
[mfapp] remove mentions of broken IGN API keys

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#236]
i know mfapp subdir should be ditched from this repo, but there are still mentions of IGN services such as `wxs.ign.fr/opbnnt8s6esy6680ptjfqmwo` (cf `wms/wmts.servers.json` which are deprecated/broken since february, and those should be moved to new urls as done for ms2 in #224

**Comment by fvanderbiest** [comment]
no mapfishapp anymore in here ...
