### ISSUE TITLE
[ms2] sync localConfig.json to enable 'searchbybookmark'

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#238]
cf https://github.com/georchestra/mapstore2-georchestra/pull/516/

**Comment by landryb** [comment]
and while at it include the localConfig.json bits from https://github.com/georchestra/mapstore2-georchestra/pull/526 too - pluginConfig.json isnt in the default datadir.

**Comment by landryb** [comment]
and https://github.com/georchestra/mapstore2-georchestra/pull/531

**Comment by fvanderbiest** [comment]
> pluginConfig.json isnt in the default datadir.

Should we add it too ?

**Comment by landryb** [comment]
> > pluginConfig.json isnt in the default datadir.
> 
> Should we add it too ?

per discussion with @offtherailz in https://github.com/georchestra/datadir/pull/224#issuecomment-981404224 im not sure it's a good idea but i know some ppl might want to customize the 'default' behaviour of plugins (i think @jusabatier did that) and doing it via `pluginsConfig.json.patch` feels a bit twisted to me.

**Comment by jusabatier** [comment]
Why not use the pluginsConfig.json defined in the datadir as a patch that will override only the attributes/options it defines ?

This way, we can simplify it by just put the options we want to override as default in this file, and the original file is stored in the webapp and upgraded with versions.

**Comment by landryb** [comment]
> Why not use the pluginsConfig.json defined in the datadir as a patch that will override only the attributes/options it defines ?

from my understanding, then it's a `pluginsConfig.json.patch` with a distinct syntax, and up to every platform admin to put whatever customization he likes... so it has no reason to be in the repo, unless commented out with a sample config ?

**Comment by jusabatier** [comment]
Isn't the `pluginsConfig.json.patch` a file from the extentions directory that is generated (and maybe overrided) by mapstore only for custom extentions (not native addons) ?

What I suggest is exactly that what we have currently with MFapp's GEOR_custom.js : a commented file that explain options and default values, where you can uncoment and set your own.
But this is a huge work and unless it's done, I suggest to simply ask/propose to tobia if it is possible to only override options that are defined in the datadir's file.

**Comment by offtherailz** [comment]
It is used for both the things. In general `pluginsConfig.json.patch` contains all the changes to apply to the original `pluginsConfig.json` and can be edited manually to apply changes and it is also generated/edited by the application to add the extensions installed.
