### ISSUE TITLE
Can i know the path for geonetwork.dir=/mnt/geonetwork_datadir

### ISSUE THREAD

**Issue by Chiranth-TL** [georchestra/datadir#241]
Hello Guys..
can any one help me understand the path here....is this from a Git or a localmachine of the developer ?
much appreciated .
Thank you

Query: geonetwork.dir=/mnt/geonetwork_datadir

**Comment by landryb** [comment]
there's https://github.com/georchestra/geonetwork_minimal_datadir/tree/gn4.0.6 but if you point geonetwork at a dir tomcat can write, it will autopopulate the directory with a default datadir. But generally speaking if you follow the doc, you should use a git-versionned folder for thedatadir.

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/datadir/blob/fafe187979838deeb8ad69cce8963497e69b3dc1/geonetwork/geonetwork.properties#L2 refers to setting in the datadir which is specific to the docker setup.
In this case, a data volume to store the geonetwork datadir (cf https://github.com/georchestra/geonetwork/blob/003bb6ba233a0406112d92c6d050f1d17aba360e/web/src/docker/Dockerfile#L18)
