### ISSUE TITLE
[datafeeder] removing scheme variable from the default.properties makes the configuration inconsistant

### ISSUE THREAD

**Issue by pmauduit** [georchestra/datadir#242]
Following https://github.com/georchestra/datadir/pull/234, the suggested configuration for the datafeeder will make it unbootable, because the `$scheme` variable no longer resolves.

Quick fix could be to have a default variable passed (like `${scheme:https}` in the DF configuration files, but it's still not clear if this syntax is ok for mail templates.

**Comment by fvanderbiest** [comment]
Quick fix suggestion: replacing `${scheme:https}` with `https` since this is the only supported scheme now ?

**Comment by fvanderbiest** [comment]
To be fixed on 22.0.x branch IIUC ?

**Comment by pmauduit** [comment]
if we don't want to have the scheme configurable, it'd make more sense to completely remove this part instead of leaving it commented out:
https://github.com/georchestra/datadir/blob/master/default.properties#L6-L9

But I am not sure of the relevance of such a move, I think that in some cases, it can be interesting to keep it configurable. there are some cases when I want to reproduce a bug and I don't want to traverse the whole stack where I could be in the need for this variable (keeping only the relevant containers from the composition, ...).

**Comment by fvanderbiest** [comment]
> if we don't want to have the scheme configurable, it'd make more sense to completely remove this part instead of leaving it commented out:
> https://github.com/georchestra/datadir/blob/master/default.properties#L6-L9

Good point

**Comment by fvanderbiest** [comment]
Done with #264 and https://github.com/georchestra/georchestra/pull/3895
