### ISSUE TITLE
remove unneeded cas/thekeystore file ?

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#247]
added in #232 but to my understanding it isnt referenced by `cas/config/cas.properties` (unless hidden defaults ? i've seen https://fawnoos.com/2018/10/22/cas6-springboot-admin-server/#spring-boot-admin-server-configuration) and the cas webapp itself doesnt handle SSL, so i think this file should be removed from the repo.

@pmauduit ?

**Comment by landryb** [comment]
i've checked, and in the current georchestra usage/configuration of cas6 everything apparently works fine with the file removed.

**Comment by pmauduit** [comment]
yes, it was provided by the upstream configuration when I started from the cas-webapp-template (https://github.com/apereo/cas-overlay-template) but is unecessary here.
