### ISSUE TITLE
geonetwork - getting rid of the geonetwork db user

### ISSUE THREAD

**Issue by pmauduit** [georchestra/datadir#253]
We historically use a dedicated user for geonetwork, so that the webapp does not mess up tables in the public schema. We actually can define the following property in the geonetwork.properties file:

```
jdbc.connectionProperties=currentSchema=geonetwork
```

and use the geochestra user instead.

**Comment by fvanderbiest** [comment]
Excellent !
That's indeed very good news

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/georchestra/blob/master/docs/setup/postgresql.md#geonetwork-schema
https://github.com/georchestra/datadir/blob/6d08850c21460d9099574a6b444f3586129e8940/geonetwork/geonetwork.properties#L63

**Comment by arnaud-morvan** [comment]
Done
