### ISSUE TITLE
[geonetwork] missing log4j2.xml

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#306]
since the upgrade to GN 4.2, there's no log4j2.xml in the `geonetwork/log4j` subdir. import it from https://github.com/georchestra/geonetwork/blob/georchestra-gn4.2.x/web/src/main/webapp/WEB-INF/classes/log4j2.xml ?

cc @pmauduit ;)

**Comment by fvanderbiest** [comment]
Good catch !
