### ISSUE TITLE
[mapstore] mettre a jour les urls IGN pour la migration vers la geoplateforme

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#307]
cf urls on https://groups.google.com/g/georchestra/c/5f7f1KYTOBk et https://geoservices.ign.fr/services-beta-geoplateforme-diffusion pour les urls temporaires... 

- mettre ces urls 'béta' en plus des existantes pour permettre les tests d'interop au fur et a mesure que l'ign alimente les nouveaux flux ?
- -faire la bascule vers les urls définitives avant le débranchement des anciennes urls fin 2023 ?

les existants ont été ajoutés en georchestra/mapstore2-georchestra#410 et #224

cc @fvanderbiest

**Comment by fvanderbiest** [comment]
On peut gérer les béta en plus, oui. Merci Landry.
