### ISSUE TITLE
[mapstore] update localConfig.json for 2023.02

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#312]
see https://github.com/georchestra/mapstore2-georchestra/commit/58f2b99ed005f6117f134a8c82471860f61d3c62 & georchestra/mapstore2-georchestra#629

**Comment by fvanderbiest** [comment]
On `master` & `docker-master` for the upcoming `23.1` ?

**Comment by landryb** [comment]
well yes, once there are proper 2023.02 releases on https://github.com/georchestra/mapstore2-georchestra/releases/, for now there's one in draft and there'll be an RC in georchestra/mapstore2-georchestra#626
