### ISSUE TITLE
console fails with java.lang.NumberFormatException: For input string: "${rabbitmqPort}"

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/datadir#336]
With the recent introduction of rabbit MQ, some new config parameters have been introduced in the [default.properties file](https://github.com/georchestra/datadir/blob/docker-master/default.properties#L60-L70). 

Since Rabbit MQ for now only addresses the usage of Gateway, I would say that we should consider it optional, since Gateway is still not the mainstream option. Considering that, it would be good if those config parameters didn't break the apps.

Right now, using the helm chart and docker-master datadir, the console fails with java.lang.NumberFormatException: For input string: "${rabbitmqPort}". 

Apparently, the issue is not rabbit MQ not being available, but simply a string to Int conversion error (when RABBITMQ_PORT is not configured). I propose we provide a default value to this env var, to prevent this error. I didn't check it on properties file, but ${RABBITMQ_PORT:-5672} works in the shell and should also work here, I'd say. And at least prevent this error.

**Comment by jeanpommier** [comment]
Ping rabbitmq guys (@edevosc2c @jeanmi151 ). Any progress on this.

AFAIK, currently, standard helm chart deployment is broken because of this, and simple docker-compose is broken because of traefik SSL certificate issue. Which means that people wanted to test georchestra using a containerized solution will conclude this is not working and move to something else.

**Comment by fvanderbiest** [comment]
> simple docker-compose is broken because of traefik SSL certificate issue

Tested working yesterday

**Comment by jeanpommier** [comment]
OK, but in the long run ?

**Comment by edevosc2c** [comment]
@jeanpommier please submit the quick solution that you proposed: `${RABBITMQ_PORT:-5672}`

And we will revise the issue later, thank you :). Don't close this github issue.

**Comment by jeanpommier** [comment]
I'd say "you broke it you fix it", but well, I'll take some time to submit it

**Comment by edevosc2c** [comment]
console and gateway just got rabbitmq disabled by default:
https://github.com/georchestra/georchestra/pull/4047
https://github.com/georchestra/georchestra-gateway/pull/62

so it shouldn't look for RABBITMQ_PORT and so on anymore.

@jeanpommier can you still reproduce the issue on georchestra master?

**Comment by jeanpommier** [comment]
Thanks @edevosc2c. I'm still having trboule with the traefik.me certifictae, but the rabbbitmq errors in console logs are not there anymore, so I'd say this is fixed. Thanks !
