### ISSUE TITLE
datafeeder - defaultResourceType

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/datadir#338]
The datafeeder-generated metadata should have
```xml
<gmd:hierarchyLevel>
<gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset"/>
</gmd:hierarchyLevel>
```
... rather than
```xml
<gmd:hierarchyLevel>
<gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode" codeListValue="series"/>
</gmd:hierarchyLevel>
```

Since https://github.com/georchestra/datadir/pull/233/files this is dynamically controlled by the `datafeeder.publishing.geonetwork.defaultResourceType` property.

All branches `master`, `docker-master`, `23.0` and `docker-23.0` have the following setting in `datafeeder.properties`:
```
# defaults to series
#datafeeder.publishing.geonetwork.defaultResourceType=dataset
```
... which is contradictory.

The default value should be "dataset" rather than "series".

**Comment by jeanmi151** [comment]
If i understand correctly it is just a matter of the comment here that need to be changed ? https://github.com/georchestra/datadir/blob/docker-master/datafeeder/datafeeder.properties#L76

**Comment by fvanderbiest** [comment]
hopefully yes

**Comment by jahow** [comment]
Also here probably: https://github.com/georchestra/georchestra/blob/41a24e9f93dbd2d69542cf8ccf35043a7af4c8df/datafeeder/src/main/java/org/georchestra/datafeeder/config/DataFeederConfigurationProperties.java#L92

**Comment by jeanmi151** [comment]
@jahow  PR created https://github.com/georchestra/georchestra/pull/4051
