### ISSUE TITLE
[datafeeder] metadata_template.xml contains eea-specific content

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/datadir#347]
- https://github.com/georchestra/datadir/blob/master/datafeeder/metadata_template.xml#L136
- https://github.com/georchestra/datadir/blob/master/datafeeder/metadata_template.xml#L156

I understand that one is supposed to adapt the files in the datadir to suit his/her needs, but it seems odd that the default template provide content that is very much specific to one platform. It should at least be documented (BTW, do we have documentation about datafeeder ?)

**Comment by fvanderbiest** [comment]
Good catch Jean !
This should indeed be fixed.

**Comment by jeanmi151** [comment]
Thanks @jeanpommier What should be the 'default values' you ?

**Comment by jeanpommier** [comment]
Hi @jeanmi151 

That's a good question. Not platform-specific for sure, but then ? I really don't know. I don't even know if there are datafeeder-specific requirements

**Comment by fvanderbiest** [comment]
Preliminary work done in #351
