### ISSUE TITLE
[datefeeder] redundant config lines

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/datadir#348]
- https://github.com/georchestra/datadir/blob/master/datafeeder/datafeeder.properties#L88
- https://github.com/georchestra/datadir/blob/master/datafeeder/datafeeder.properties#L98

Is there a typo in the first one ? Should it be `datafeeder.publishing.backend.local.schema=<schema>` ?

**Comment by landryb** [comment]
fixed by #360 ?

**Comment by jeanpommier** [comment]
I guess so ;o)
