### ISSUE TITLE
homepage.url not found in cas.properties

### ISSUE THREAD

**Issue by landryb** [georchestra/datadir#4]
https://github.com/georchestra/template/blob/master/cas-server-webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L46 looks for a `homepage.url` value in `cas.properties`, which isnt present in https://github.com/georchestra/config/blob/master/cas/cas.properties. Either `homepage.url` should be added there, or the top.jsp could use `server.name`.

I think this breaks redirect-to-homepage when you login directly on /cas/login.

**Comment by fvanderbiest** [comment]
Should be addressed with https://github.com/georchestra/datadir/commit/4bd5637ec4708579f436703b06fc3f443ae9ba33
