### ISSUE TITLE
sec-org header

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/datadir#40]
Currently, the datadir (master branch) is not in a coherent state with the security-proxy code (master branch too) , since the `sec-org` header is set twice:
 *  once to the inetOrgPerson's `o` field with https://github.com/georchestra/datadir/blob/master/security-proxy/headers-mapping.properties#L4
 * a second time to the `cn` attribute of the linked org with https://github.com/georchestra/georchestra/blob/master/security-proxy/src/main/java/org/georchestra/security/LdapUserDetailsRequestHeaderProvider.java#L156 (eg https://github.com/georchestra/georchestra/blob/master/ldap/georchestra.ldif#L208)

Several options here:
 * remove the `sec-org=o` header mapping,
 * keep the line, but rename the sec-org header (the one mapping to the user's `o` field) to `sec-orgname`

One question to @Vampouille : what links the user's `o` field and his org's `cn` field ?

**Comment by Vampouille** [comment]
We can add a header in security proxy with human readable organism name and remove `sec-orgname=o`

**Comment by fvanderbiest** [comment]
> One question to @Vampouille : what links the user's o field and his org's cn field ?

Nothing right now, which makes it a good option to remove the `sec-orgname=o` mapping from https://github.com/georchestra/datadir/blob/master/security-proxy/headers-mapping.properties

**Comment by fvanderbiest** [comment]
> add a static header sec-orgname in security proxy

This should also facilitate logging of the real org title by ogc-server-statistics, and improve the current rendering in the console:
![capture du 2017-01-17 12 38 59](https://cloud.githubusercontent.com/assets/265319/22019021/f67d1744-dcb1-11e6-9375-68fbe6c3e9c3.png)

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/datadir/pull/51
