### ISSUE TITLE
add local geoserver in mapfishapp/wms.servers.json ?

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/datadir#55]
do you think that adding the local geoserver in mapfishapp/wms.servers.json should be a good idea ? 

        {
            "name": "My local WMS geoserver",
            "url": "https://georchestra.mydomain.org/geoserver/wms"
        }

I think it would be very useful for everyone.

**Comment by fvanderbiest** [comment]
+1 !
Also wfs, wmts and csw ...

PR welcome.

**Comment by MaxiReglisse** [comment]
it is already done for CSW, in mapfishapp/js/GEOR_custom.js

        ['/geonetwork/srv/fre/csw', 'le catalogue local'],
but it does not work for me in WMTS... i dot knwo why.

**Comment by landryb** [comment]
Fwiw, it was mostly done in 18171678 where /geoserver/xxx was added to {wms,wfs,wmts}.servers.json but unfortunately at runtime it doesnt work, the add layer dialog complains that '/geoserver/wms' is a malformed URL... without fqdn :)

**Comment by fvanderbiest** [comment]
Oops, my bad...
