### ISSUE TITLE
Il manque un slash après admin

### ISSUE THREAD

**Issue by alainbenard** [georchestra/datadir#68]
https://github.com/georchestra/datadir/blob/0b0867bd5113b5a26073fa2d7cd654e6ecc42aa9/security-proxy/security-mappings.xml#L4

**Comment by fvanderbiest** [comment]
Thanks for the report, but nope, this was intentional, see 6ae33ae8e65f291a6080b2fe91ea000dfd74858b
IIRC, the SP did not protect direct access to /extractorapp/admin/ but /extractorapp/admin was allowed hence the change.
