### ISSUE TITLE
nomenclature - replace headerUrl by headerPath

### ISSUE THREAD

**Issue by severo** [georchestra/datadir#98]
Now that @bortzmeyer is looking at us, I think we should care the variables names :)

https://github.com/georchestra/datadir/blob/d093d795aa7d824a72acb749750f67fcedc28418/default.properties#L9

should be named `headerPath` and not `headerUrl`.

See https://en.wikipedia.org/wiki/URL#Syntax:

> `URI = scheme:[//authority]path[?query][#fragment]`

**Comment by fvanderbiest** [comment]
It currently is set to a path indeed, but it can also be used for a URL (see eg https://github.com/georchestra/georchestra/blob/a1a9a125a88367bbaf77918cdd202f75ddc3854c/mapfishapp/src/main/webapp/WEB-INF/jsp/header.jsp#L34 )

**Comment by severo** [comment]
hmmm, correct. I close.
